include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    #implicit-dynamic: false
  exclude:
    '**/*.g.dart'

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    always_use_package_imports: true
    use_key_in_widget_constructors: true
